"""Weft SDK — stdlib-only Python client for the Weft A2A protocol."""

from .client import (
    WeftClient,
    WeftError,
    AuthError,
    EvidenceError,
    NotFoundError,
    ConflictError,
    TimeoutError,
    TaskResult,
    PairingResult,
    JoinResult,
    SessionEvent,
    CredentialRotation,
    RoomResult,
    RoomJoinResult,
    RoomInfo,
    RoomMember,
    RoomEvent,
    RoomPoll,
    RoomSendResult,
)

__all__ = [
    "WeftClient",
    "WeftError",
    "AuthError",
    "EvidenceError",
    "NotFoundError",
    "ConflictError",
    "TimeoutError",
    "TaskResult",
    "PairingResult",
    "JoinResult",
    "SessionEvent",
    "CredentialRotation",
    "RoomResult",
    "RoomJoinResult",
    "RoomInfo",
    "RoomMember",
    "RoomEvent",
    "RoomPoll",
    "RoomSendResult",
]
